# Generated by Django 6.0 on 2025-12-14 09:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordre', 'nom_categorie'],
            },
        ),
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('nom_proprietaire', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='artisans/logos/%Y/%m/')),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('localisation_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('localisation_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('horaires', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('certifie', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('nombre_favoris', models.PositiveIntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artisans', to='marketplaceapp.categorie')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ArtisanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artisans/images/%Y/%m/')),
                ('type_image', models.CharField(default='galerie', max_length=50)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplaceapp.artisan')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/%Y/%m/')),
                ('categorie_produit', models.CharField(blank=True, max_length=100, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('en_promotion', models.BooleanField(default=False)),
                ('prix_promotion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('nombre_commandes', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='marketplaceapp.artisan')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_rubrique', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubriques', to='marketplaceapp.categorie')),
            ],
            options={
                'ordering': ['nom_rubrique'],
                'unique_together': {('categorie', 'nom_rubrique')},
            },
        ),
        migrations.AddField(
            model_name='artisan',
            name='rubrique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisans', to='marketplaceapp.rubrique'),
        ),
        migrations.CreateModel(
            name='StatistiqueArtisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('nombre_favoris', models.PositiveIntegerField(default=0)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('artisan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='marketplaceapp.artisan')),
            ],
        ),
    ]
