# Generated by Django 6.0 on 2025-12-14 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0002_alter_artisan_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie_produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='en_promotion',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nombre_commandes',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nombre_vues',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_promotion',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/')),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplaceapp.produit')),
            ],
            options={
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
