# Generated by Django 6.0 on 2025-12-14 20:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0003_alter_produit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduit',
            options={'ordering': ['ordre', 'date_ajout'], 'verbose_name': 'Image de produit', 'verbose_name_plural': 'Images de produits'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='marketplaceapp.categorie'),
        ),
        migrations.AlterField(
            model_name='imageproduit',
            name='image',
            field=models.ImageField(upload_to='produits/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
