# Generated by Django 6.0 on 2025-12-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artisans', to='marketplaceapp.categorie'),
        ),
    ]
