# Generated by Django 6.0 on 2025-12-16 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0006_alter_artisan_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('pays_preference', models.CharField(default='Cameroun', max_length=100)),
                ('rayon_recherche_km', models.IntegerField(default=10)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recevoir_nouveautes', models.BooleanField(default=True)),
                ('recevoir_promotions', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categories_preferees', models.ManyToManyField(blank=True, related_name='clients_interesses', to='marketplaceapp.categorie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Client',
                'verbose_name_plural': 'Profils Clients',
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('note_personnelle', models.TextField(blank=True, null=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_recus', to='marketplaceapp.artisan')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('client', 'artisan')},
            },
        ),
    ]
