# Generated by Django 6.0 on 2025-12-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0007_profilclient_favori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilclient',
            name='categories_preferees',
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='ville_preference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
