# Generated by Django 6.0 on 2025-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceapp', '0008_remove_profilclient_categories_preferees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilclient',
            name='categories_preferees',
            field=models.ManyToManyField(blank=True, related_name='clients_interesses', to='marketplaceapp.categorie'),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='ville_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
