"""
Django settings for marketplace project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-(-b@do5hrv@s57n-44lw6j10z$!8f@t)m4)p(22-8dz06k(%^4'
DEBUG = True
ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'marketplaceapp',  # ton app
    'corsheaders',     # <-- ajout pour CORS
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <-- doit être en haut
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketplace.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = 'static/'


# =========================
# CORS Settings
# =========================
# Autoriser seulement ton frontend
CORS_ALLOW_ALL_ORIGINS = True

# Autoriser certains headers si nécessaire
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
]

# Autoriser certaines méthodes
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]
# Static files
STATIC_URL = 'static/'


# =========================
# CORS Settings
# =========================
# ... (votre configuration CORS existante) ...


# =========================
# MEDIA Files (Fichiers téléchargés par les utilisateurs)
# =========================
# L'URL utilisée pour accéder aux fichiers média (images KYC, etc.)
MEDIA_URL = '/media/'

# Le chemin physique complet où les fichiers média seront stockés
# Cela crée un dossier 'media' à la racine de votre projet.
MEDIA_ROOT = BASE_DIR / 'media'